"""add cpu_per_core to system_metrics

Revision ID: ace44c995def
Revises: d65138d09d36
Create Date: 2026-08-11 12:31:25.018427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace44c995def'
down_revision: Union[str, Sequence[str], None] = 'd65138d09d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_per_core', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.drop_column('cpu_per_core')

    # ### end Alembic commands ###
