"""add system load 5 and 15 minute averages

Revision ID: d65138d09d36
Revises: e992e8112e5c
Create Date: 2026-08-10 16:45:45.517306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65138d09d36'
down_revision: Union[str, Sequence[str], None] = 'e992e8112e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('load_avg_5', sa.Float(), nullable=False, server_default=sa.text("0.0")))
        batch_op.add_column(sa.Column('load_avg_15', sa.Float(), nullable=False, server_default=sa.text("0.0")))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.drop_column('load_avg_15')
        batch_op.drop_column('load_avg_5')

    # ### end Alembic commands ###
