"""initial schema

Revision ID: e992e8112e5c
Revises: 
Create Date: 2026-08-10 16:25:19.235949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e992e8112e5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('innodb_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buffer_hit_ratio', sa.Float(), nullable=False),
    sa.Column('deadlocks', sa.Integer(), nullable=False),
    sa.Column('dirty_pages', sa.Integer(), nullable=False),
    sa.Column('pending_io', sa.Integer(), nullable=False),
    sa.Column('history_list_len', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mysql_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('threads_connected', sa.Integer(), nullable=True),
    sa.Column('max_connections', sa.Integer(), nullable=True),
    sa.Column('database_size_bytes', sa.Integer(), nullable=True),
    sa.Column('innodb_buffer_pool_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname', 'port', name='uq_server_host_port')
    )
    op.create_table('process_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_name', sa.String(length=64), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('memory_rss', sa.Integer(), nullable=False),
    sa.Column('threads', sa.Integer(), nullable=False),
    sa.Column('open_files', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=False),
    sa.Column('load_avg', sa.Float(), nullable=False),
    sa.Column('cpu_freq', sa.Float(), nullable=True),
    sa.Column('mem_total', sa.Integer(), nullable=False),
    sa.Column('mem_used', sa.Integer(), nullable=False),
    sa.Column('mem_avail', sa.Integer(), nullable=False),
    sa.Column('swap_used', sa.Integer(), nullable=False),
    sa.Column('swap_total', sa.Integer(), nullable=False),
    sa.Column('disk_used', sa.Integer(), nullable=False),
    sa.Column('disk_total', sa.Integer(), nullable=False),
    sa.Column('disk_read', sa.Integer(), nullable=False),
    sa.Column('disk_write', sa.Integer(), nullable=False),
    sa.Column('net_in', sa.Integer(), nullable=False),
    sa.Column('net_out', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('schema_name', sa.String(length=64), nullable=True),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('total_ms', sa.Float(), nullable=False),
    sa.Column('avg_ms', sa.Float(), nullable=False),
    sa.Column('max_ms', sa.Float(), nullable=False),
    sa.Column('rows_examined', sa.Integer(), nullable=False),
    sa.Column('rows_sent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['mysql_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_stats')
    op.drop_table('system_metrics')
    op.drop_table('reports')
    op.drop_table('recommendations')
    op.drop_table('process_metrics')
    op.drop_table('mysql_servers')
    op.drop_table('innodb_metrics')
    op.drop_table('alerts')
    # ### end Alembic commands ###
